### ISSUE TITLE
缺少中文文字图片

### ISSUE THREAD

**Issue by Congdan** [HellSakura/UpdateWeather#1]
Traceback (most recent call last):
  File "/Users/huangcongdan/Downloads/UpdateWeather/UpdateWeather.py", line 232, in <module>
    weather_image = Image.open(image_path + textDay + ".png")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/huangcongdan/Downloads/UpdateWeather/img/小到中雨.png'

运行时发现少了一些中文文字图片，可以添加进去吗？或者请问你在哪里获得这些图片的，我自己添加进去吧

**Comment by HellSakura** [comment]
图片是自己生成的像素字，尺寸为64X24，对于这个墨水屏幕，4个像素点作为一个像素使用最佳     
部分图片我没有找的合适的像素字体来生成，尤其是4字以上天气，你可以自己添加后使用，放置于目录下的img文件夹中

具体天气状况在这里-[天气图标](https://dev.qweather.com/docs/resource/icons/#%E5%A4%A9%E6%B0%94%E5%9B%BE%E6%A0%87)
单个像素也可以使用，只是显示效果没有那么好罢了

**Comment by HellSakura** [comment]
单像素生成的图片效果参考 img文件夹中的[特大暴雨.png](https://github.com/HellSakura/UpdateWeather/blob/main/img/%E7%89%B9%E5%A4%A7%E6%9A%B4%E9%9B%A8.png)

**Comment by Congdan** [comment]
你用的是什么软件来生成像素字？

**Comment by HellSakura** [comment]
> 你用的是什么软件来生成像素字？

嗯...我是用的  Adobe Illustrator ，你可以试试 Aseprite ，相对来说比较简单

**Comment by Congdan** [comment]
好的，谢谢，我研究一下
