### ISSUE TITLE
发现翻着墙时，无法更新天气

### ISSUE THREAD

**Issue by rrtt2323** [HellSakura/UpdateWeather#7]
![image](https://github.com/HellSakura/UpdateWeather/assets/12709491/2c3411a8-e024-4fc2-a333-fb138b415e8b)
![image](https://github.com/HellSakura/UpdateWeather/assets/12709491/138d0943-98b3-4f1b-ba54-ce9bf26cfe2b)

**Comment by HellSakura** [comment]
这是因为`urllib`库没有正确配置 HTTPS 代理，一般情况下只需要额外添加一个proxy配置即可，但考虑到大部分人不会日常使用翻墙工具，故禁用SSL以允许 HTTPS 连接在没有证书的情况下也能成功链接
